### ISSUE TITLE
toot should not open Mastodon instance in a new tab

### ISSUE THREAD

**Issue by andybalaam** [NickKaramoff/toot#3]
When I use shareon's new Mastodon button, it opens toot in a new browser tab. Then, when I click Toot! in toot, it opens another browser tab.

I think that once I click Toot!, I am finished with toot for now, so it should open the Mastodon instance in the same tab.

What do you think?

**Comment by NickKaramoff** [comment]
You're absolutely right 😁 I'll check the PR now
