### ISSUE TITLE
Style select drop-down list for instances in some way

### ISSUE THREAD

**Issue by janopae** [NickKaramoff/toot#7]
In general, I like UI elements on websites being unstyled and looking like the operating system theme. However, when I first used toot, I thought the drop down was one provided by my browser, remembering things I typed into text fields on other websites, until I read it's content and realised it was actually a very useful list of mastodon instances.

Obviously, so many websites style their drop-downs, that my brain automatically thought that this could not be part of the website.

That's why I propose applying some CSS to it, in order to make it look dark and part of the page. @NickKaramoff What do you think about this?

**Comment by NickKaramoff** [comment]
AFAIK there is no simple and consistent way to style browser's default dropdowns (such as `<input list="...">`, which I am using). [MDN suggests a way](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist#customizing_datalist_styles), but it only works in Chrome.

I could consider using a non-semantic way of doing this (that is, with custom `<div>`s), although I am really not a fan of such solutions. I'll try looking into that.

**Comment by NickKaramoff** [comment]
Closing this issue due to the lack of options really. There is no way to style this drop-down that isn't hacky. I don't want my website to bundle a ton of JavaScript, so I'll leave it to the browser vendors ¯\_(ツ)_/¯
